### ISSUE TITLE
spring-boot-configmaps-demo fails deployment due to missing image on Dockerhub

### ISSUE THREAD

**Issue by quantum-fusion** [redhat-developer-demos/spring-boot-configmaps-demo#1]
The problem is that your image in the spring-boot-configmaps-demo for developers/spring-boot-configmaps-demo:latest on Dockerhub is missing.

Therefore the deploy command (./mvnw clean fabric8:deploy) fails.

-----
spring-boot-configmaps-demo-675c4d45c7-bjlx7   0/1       ImagePullBackOff   0          48s
MacBook-Pro:~/Desktop/spring-boot-configmaps-demo-master quantum-fusion$ kubectl describe pod spring-boot-configmaps-demo-675c4d45c7-bjlx7
Name:           spring-boot-configmaps-demo-675c4d45c7-bjlx7
Namespace:      default
Node:           minikube/10.0.2.15
Start Time:     Wed, 04 Jul 2018 09:59:12 -0400
Labels:         app=spring-boot-configmaps-demo
                group=com.redhat.developers
                pod-template-hash=2317080173
                provider=fabric8
                version=0.0.1-SNAPSHOT
Annotations:    fabric8.io/git-branch=master
                fabric8.io/git-commit=cc837910332660d4374ac653fa88072ecaa2d51f
                fabric8.io/iconUrl=img/icons/spring-boot.svg
                fabric8.io/metrics-path=dashboard/file/kubernetes-pods.json/?var-project=spring-boot-configmaps-demo&var-version=0.0.1-SNAPSHOT
                fabric8.io/scm-tag=HEAD
                fabric8.io/scm-url=https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/spring-boot-configmaps-demo
Status:         Pending
IP:             172.17.0.7
Controlled By:  ReplicaSet/spring-boot-configmaps-demo-675c4d45c7
Containers:
  spring-boot:
    Container ID:   
    Image:          developers/spring-boot-configmaps-demo:snapshot-180704-095903-0502
    Image ID:       
    Ports:          8080/TCP, 9779/TCP, 8778/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:8080/health delay=180s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:8080/health delay=10s timeout=1s period=10s #success=1 #failure=3
    Environment:
      GREETING_PREFIX:       <set to the key 'greeter.prefix' of config map 'spring-boot-configmaps-demo'>  Optional: false
      KUBERNETES_NAMESPACE:  default (v1:metadata.namespace)
    Mounts:
      /deployments/config from application-config (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-4fbcc (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  application-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      spring-app-config
    Optional:  false
  default-token-4fbcc:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-4fbcc
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age              From               Message
  ----     ------                 ----             ----               -------
  Normal   Scheduled              2m               default-scheduler  Successfully assigned spring-boot-configmaps-demo-675c4d45c7-bjlx7 to minikube
  Normal   SuccessfulMountVolume  2m               kubelet, minikube  MountVolume.SetUp succeeded for volume "application-config"
  Normal   SuccessfulMountVolume  2m               kubelet, minikube  MountVolume.SetUp succeeded for volume "default-token-4fbcc"
  Normal   Pulling                1m (x4 over 2m)  kubelet, minikube  pulling image "developers/spring-boot-configmaps-demo:snapshot-180704-095903-0502"
  Warning  Failed                 1m (x4 over 2m)  kubelet, minikube  Failed to pull image "developers/spring-boot-configmaps-demo:snapshot-180704-095903-0502": rpc error: code = Unknown desc = Error response from daemon: pull access denied for developers/spring-boot-configmaps-demo, repository does not exist or may require 'docker login'
  Warning  Failed                 1m (x4 over 2m)  kubelet, minikube  Error: ErrImagePull
  Normal   BackOff                1m (x5 over 2m)  kubelet, minikube  Back-off pulling image "developers/spring-boot-configmaps-demo:snapshot-180704-095903-0502"
  Warning  Failed                 1m (x6 over 2m)  kubelet, minikube  Error: ImagePullBackOff

**Comment by quantum-fusion** [comment]
@kameshsampath I reviewed the project files, and do not see any reference to developers/spring-boot-configmaps-demo:latest , where the deploy command does the push deployment to docker hub.  Why should the deploy step fail if that project isn't referenced, and isn't this a bug in the deploy command?  Where is the reference to developers/spring-boot-configmaps-demo , and can't it be changed to a local docker hub account ?  Please advise, because this is causing deployment to fail.

**Comment by kameshsampath** [comment]
the images are built locally and no images are available in Docker Hub, with fabric8-maven-plugin and you having access the DOCKER_HOST then just run `mvn clean package fabric8:deploy`
