### ISSUE TITLE
spring-boot-configmaps-demo fabric8 plugin failed to deploy 

### ISSUE THREAD

**Issue by quantum-fusion** [redhat-developer-demos/spring-boot-configmaps-demo#2]
I executed this command to build locally, mvn clean package fabric8:deploy

However, the pod still thinks it has to pull from developers/spring-boot-configmaps-demo

kubectl get pods -w
NAME                                           READY     STATUS             RESTARTS   AGE
spring-boot-configmaps-demo-78b95f7688-d6pql   0/1       ImagePullBackOff   0          14s
^CMacBook-Pro:~/Desktop/spring-boot-configmaps-demo-master quantum-fusion$ kubectl describe pods spring-boot-configmaps-demo-78b95f88-d6pql
Name:           spring-boot-configmaps-demo-78b95f7688-d6pql
Namespace:      default
Node:           minikube/10.0.2.15
Start Time:     Wed, 04 Jul 2018 12:15:02 -0400
Labels:         app=spring-boot-configmaps-demo
                group=com.redhat.developers
                pod-template-hash=3465193244
                provider=fabric8
                version=0.0.1-SNAPSHOT
Annotations:    fabric8.io/git-branch=master
                fabric8.io/git-commit=cc837910332660d4374ac653fa88072ecaa2d51f
                fabric8.io/iconUrl=img/icons/spring-boot.svg
                fabric8.io/metrics-path=dashboard/file/kubernetes-pods.json/?var-project=spring-boot-configmaps-demo&var-version=0.0.1-SNAPSHOT
                fabric8.io/scm-tag=HEAD
                fabric8.io/scm-url=https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/spring-boot-configmaps-demo
Status:         Pending
IP:             172.17.0.5
Controlled By:  ReplicaSet/spring-boot-configmaps-demo-78b95f7688
Containers:
  spring-boot:
    Container ID:   
    Image:          developers/spring-boot-configmaps-demo:snapshot-180704-121459-0587
    Image ID:       
    Ports:          8080/TCP, 9779/TCP, 8778/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP
    State:          Waiting
      Reason:       ErrImagePull
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:8080/health delay=180s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:8080/health delay=10s timeout=1s period=10s #success=1 #failure=3
    Environment:
      GREETING_PREFIX:       <set to the key 'greeter.prefix' of config map 'spring-boot-configmaps-demo'>  Optional: false
      KUBERNETES_NAMESPACE:  default (v1:metadata.namespace)
    Mounts:
      /deployments/config from application-config (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-4fbcc (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  application-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      spring-app-config
    Optional:  false
  default-token-4fbcc:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-4fbcc
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age                From               Message
  ----     ------                 ----               ----               -------
  Normal   Scheduled              40s                default-scheduler  Successfully assigned spring-boot-configmaps-demo-78b95f7688-d6pql to minikube
  Normal   SuccessfulMountVolume  40s                kubelet, minikube  MountVolume.SetUp succeeded for volume "application-config"
  Normal   SuccessfulMountVolume  40s                kubelet, minikube  MountVolume.SetUp succeeded for volume "default-token-4fbcc"
  Normal   Pulling                26s (x2 over 40s)  kubelet, minikube  pulling image "developers/spring-boot-configmaps-demo:snapshot-180704-121459-0587"
  Warning  Failed                 25s (x2 over 39s)  kubelet, minikube  Failed to pull image "developers/spring-boot-configmaps-demo:snapshot-180704-121459-0587": rpc error: code = Unknown desc = Error response from daemon: pull access denied for developers/spring-boot-configmaps-demo, repository does not exist or may require 'docker login'
  Warning  Failed                 25s (x2 over 39s)  kubelet, minikube  Error: ErrImagePull
  Normal   BackOff                12s (x2 over 39s)  kubelet, minikube  Back-off pulling image "developers/spring-boot-configmaps-demo:snapshot-180704-121459-0587"
  Warning  Failed                 12s (x2 over 39s)  kubelet, minikube  Error: ImagePullBackOff

**Comment by quantum-fusion** [comment]
@kameshsampath I tried using the fabric8:deploy command that you specified, however see "Warning Failed 25s (x2 over 39s) kubelet, minikube Failed to pull image "developers/spring-boot-configmaps-demo:snapshot-180704-121459-0587": rpc error: code = Unknown desc = Error response from daemon: pull access denied for developers/spring-boot-configmaps-demo, repository does not exist or may require 'docker login'"

**Comment by kameshsampath** [comment]
@quantum-fusion  - you need to do a `mvn clean package` before you do a build since thats where the needed **FROM** docker image `developers/spring-boot-configmaps-demo:snapshot-180704-121459-0587` is built.  `developers/spring-boot-configmaps-demo` is the custom name given by the farbic8 maven plugin - the `developers` is the last fragment of the package name and there is no repo exists in docker hub. all images are built locally.

**Comment by quantum-fusion** [comment]
@kameshsampath I investigated setting up a local registry with Kubernetes, however even with the local registry, it would not build successfully, and still produces the error.  You might publish the configuration you are using to get the docker image built, and pulled, because minikube is assuming that it pulls from a public registry by default, and that is the error that it is producing. "pull access denied for developers/spring-boot-configmaps-demo, repository does not exist or may require 'docker login'"

Steps to Setup Minikube and setup a local registry.
https://sdqali.in/blog/2016/11/04/a-very-basic-introduction-to-deploying-a-java-application-using-kubernetes/
https://docs.docker.com/machine/reference/create/#example
docker-machine create --driver virtualbox registry

Missing steps: 
kubectl create configmap spring-app-config --from-file=src/main/resources/application.properties

Setting up ConfigMap with Kubernetes:
https://developers.redhat.com/blog/2017/10/03/configuring-spring-boot-kubernetes-configmap/

Kubernetes Secrets and ConfigMaps
https://medium.com/google-cloud/kubernetes-configmaps-and-secrets-68d061f7ab5b
https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables
https://developers.redhat.com/blog/2017/10/04/configuring-spring-boot-kubernetes-secrets/

Other Resources:
https://stackoverflow.com/questions/34848422/how-to-debug-imagepullbackoff
kubectl describe pod myPod

**Comment by kameshsampath** [comment]
I guess you are getting confused with setting up registry and other stuff. It does not require so much complication. If you are on minikube then please run `eval $(minishift minkube-env)` to allow your host to connect to minkube docker daemon and other env variables. If you are on minishift then you need to do `eval $(minishift min-env) && eval $(minishift oc-env)` to get the right DOCKER + OpenShif CLI . 

Either of these commands helps you in getting the right DOCKER environment variables setup that allows to fabric8-maven-plugin to build and push the image  minikube/minishift docker registry. Mostly you should be knowing that minikube and minishift both comes with docker registries already so you don't need to set one.

**Comment by quantum-fusion** [comment]
@kameshsampath I installed minishift, however it doesn't recognize the minkube-env.
https://docs.openshift.org/latest/minishift/getting-started/installing.html
brew cask install minishift

1.) Do you know the complete commands to get the cluster started?  
2.) Are you going to use minikube OR are you going to use minishift with OpenShift?

Please provide the detailed commands that have been tested that you know works.

----
eval $(minishift minkube-env)
Error: unknown command "minkube-env" for "minishift"
Run 'minishift --help' for usage.
unknown command "minikube-env" for "minishift"
MacBook-Pro:~ quantum-fusion$ minishift --help
Minishift is a command-line tool that provisions and manages single-node OpenShift clusters optimized for development workflows.

Usage:
  minishift [command]

Available Commands:
  addons      Manages Minishift add-ons.
  completion  Outputs minishift shell completion for the given shell (bash or zsh)
  config      Modifies Minishift configuration properties.
  console     Opens or displays the OpenShift Web Console URL.
  delete      Deletes the Minishift VM.
  docker-env  Sets Docker environment variables.
  help        Help about any command
  hostfolder  Manages host folders for the Minishift VM.
  image       Exports and imports container images.
  ip          Gets the IP address of the running cluster.
  logs        Gets the logs of the running OpenShift cluster.
  oc-env      Sets the path of the 'oc' binary.
  openshift   Interacts with your local OpenShift cluster.
  profile     Manages Minishift profiles.
  ssh         Log in to or run a command on a Minishift VM with SSH.
  start       Starts a local OpenShift cluster.
  status      Gets the status of the local OpenShift cluster.
  stop        Stops the running local OpenShift cluster.
  update      Updates Minishift to the latest version.
  version     Gets the version of Minishift.

Flags:
      --alsologtostderr                  log to standard error as well as files
  -h, --help                             help for minishift
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory (default "")
      --logtostderr                      log to standard error instead of files
      --profile string                   Profile name (default "minishift")
      --show-libmachine-logs             Show logs from libmachine.
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          log level for V logs
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

Use "minishift [command] --help" for more information about a command.

**Comment by quantum-fusion** [comment]
https://docs.openshift.org/latest/minishift/getting-started/quickstart.html

OR

https://kubernetes.io/docs/setup/minikube/

**Comment by kameshsampath** [comment]
@quantum-fusion  -  i guess you have misunderstood my commands:

Assuming you are on Linux/macOS base envs:

**MINISHIFT**

you have to `eval $(minishift docker-env) && eval $(minishift oc-env)` from all terminals from where you might be ruinning fabric8 maven plugin goals

**MINIKUBE**

you have to `eval $(minikube docker-env)`  from all terminals from where you might be ruinning fabric8 maven plugin goals

The `minishift docker-env` or `minikube docker-env` are the util commands to set the OpenShift/Kubernetes `DOCKER_*` env variables, which enables your Docker builds to connect to right docker daemon.

> I installed minishift, however it doesn't recognize the minkube-env. 
minikube commands will no work on minishift. Please refer to the commands above.


> Do you know the complete commands to get the cluster started? 
```
$ minishift profile set mydemo # give any name you like for the profile
$ minishift config set memory 8GB # giving 8GB for the kube cluster, change to whatever you want
$ minishift config set cpus 3 # giving 3 vCPUs
$ minishift config set image-caching true # allowing to cache downloaded images 
$ minishift addon enable admin-user # just to add admin user in the cluster
$ minishift start
```

Give the `admin` user you can do login like `$ oc login -u admin -p admin  --server <your minishift erver> ` - admin user has cluster admin role imagine like linux super user.

**Comment by quantum-fusion** [comment]
This looks much better now, after starting mini shift start, it knows how to load the registry, and to deploy to mini shift, and open shift.  

See transcript history:
minishift config set memory 8GB
minishift config set cpus 3
minishift config set image-caching true
minishift addon enable admin-user
minishift start
oc login -u system:admin
eval $(minishift docker-env) && eval $(minishift oc-env)
eval $(minikube docker-env)
mvn clean package fabric8:deploy
oc get pods -w

See results: 
NAME                                      READY     STATUS              RESTARTS   AGE
spring-boot-configmaps-demo-1-deploy      1/1       Running             0          5m
spring-boot-configmaps-demo-1-knf59       0/1       ContainerCreating   0          5m
spring-boot-configmaps-demo-s2i-1-build   0/1       Completed           0          6m

**Comment by quantum-fusion** [comment]
The one exception, is that it doesn't know how to do: %eval $(minikube docker-env)

eval $(minikube docker-env)
E0707 07:10:36.839002   16330 env.go:330] Error setting machine env variable(s): Error getting ip from host: Host is not running
-bash: ================================================================================: command not found

**Comment by kameshsampath** [comment]
minishift will not install minikube binary, as said earlier for minishift its enough you run the `eval $(minishift docker-env) && eval $(minishift oc-env)`

I hope this solves all your issues. if so please close this ticket. 

thank you.

**Comment by quantum-fusion** [comment]
@kameshsampath I haven't tested your project spring-boot-configmaps-demo, however the results that I posted show that the container is now running. It is suspicious that there are two extra pods that were created, spring-boot-configmaps-demo-1-knf59 that never actually creates the container, and also spring-boot-configmaps-demo-s2i-1-build that completed.

See results:
NAME READY STATUS RESTARTS AGE
spring-boot-configmaps-demo-1-deploy 1/1 Running 0 5m
spring-boot-configmaps-demo-1-knf59 0/1 ContainerCreating 0 5m
spring-boot-configmaps-demo-s2i-1-build 0/1 Completed 0 6m
